[package]
name = "phase2"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "zk-SNARK MPC"
documentation = "https://github.com/ebfull/phase2"
homepage = "https://github.com/ebfull/phase2"
license = "MIT/Apache-2.0"
repository = "https://github.com/ebfull/phase2"

[dependencies]
pairing = "0.14"
rand = "0.4"
bellman = "0.1"
byteorder = "1"
blake2 = "0.6.1"
num_cpus = "1"
crossbeam = "0.3"
generic-array = "0.8.3"
typenum = "1.9.0"
