[package]
name = "powersoftau"
version = "0.2.0"
authors = ["Sean Bowe", "Alex Vlasov"]
license = "MIT/Apache-2.0"
edition = "2018"

description = "Communal zk-SNARK MPC for Public Parameters"
documentation = "https://docs.rs/powersoftau/"
homepage = "https://github.com/matter-labs/powersoftau"
repository = "https://github.com/matter-labs/powersoftau"

[dependencies]
rand = "0.4"
crossbeam = "0.3.0"
num_cpus = "1.7.0"
blake2 = "0.6.1"
generic-array = "0.8.3"
typenum = "1.9.0"
byteorder = "1.1.0"
hex-literal = "0.1.4"
rust-crypto = "0.2"
exitcode = "1.1.2"

memmap = "0.7.0"
itertools = "0.8.0"

bellman_ce = { version = "0.3.1", default-features = false, features = ["multicore"] }
log = "0.4.8"
gumdrop = "0.7.0"
rayon = "1.3.0"
