[package]
name = "test-helpers"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snark-utils = { path = "../snark-utils" }
zexe_algebra = { package = "algebra", version = "0.1.0", features = ["parallel"] }

rand = "0.7.3"
typenum = "1.9.0"
rust-crypto = "0.2"
generic-array = "0.8.3"